jobs:
  build:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run:
          name: Scan Docker image with trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ~/bin
      - run:
          name: Scan the local image with trivy
          command: ~/bin/trivy image python:3.4-alpine
      - run:
          name: Scan with GitLeaks
          command: bash <(curl -s https://raw.githubusercontent.com/zricethezav/gitleaks-ci/master/gitleaks.sh)
      - run:
          name: Install Composer
          command: |
            echo '{ "require": { "php": ">=7.2" } }' >> composer.json
            composer install
      - run:
          name: Run security checker
          command: |
            wget https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.6/local-php-security-checker_2.0.6_linux_386
            ./local-php-security-checker_2.0.6_linux_386
      # - run:
      #     name: Run static analysis
      #     command: composer require --dev phpstan/phpstan && php vendor/bin/phpstan analyze --level=max src/
workflows:
  version: 2
  release:
    jobs:
      - build